on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xt0rted/markdownlint-problem-matcher@v3
      - run: npm install -g markdownlint-cli
      - run: markdownlint **/*.md --ignore node_modules
